### ISSUE TITLE
Tinty custom generated schemes not recognized

### ISSUE THREAD

**Issue by hadallen** [tinted-theming/tinted-nvim#18]
Hi, I found that custom generated schemes are not recognized by the neovim plugin, only built-in colorschemes are found. 

I have set up tinted-nvim in my `tinty` config.toml and have as well added the `tinted-theming/tinted-nvim` neovim plugin, and created a custom generated scheme (using `tinty generate-schema --save --system=base16 /path/to/img.png`)

A workaround is to use the .vim file method found in the [`tinty` USAGE.md](https://github.com/tinted-theming/tinty/blob/main/USAGE.md#without-base16-vim-setup-in-vimneovim). I've set the theme script path to the generated file directly: 

```lua
local theme_script_path = vim.fn.expand("~/.local/share/tinted-theming/tinty/repos/neovim/colors/base24-tinty-generated.vim")

local function file_exists(file_path)
  return vim.fn.filereadable(file_path) == 1 and true or false
end

local function handle_focus_gained()
  if file_exists(theme_script_path) then
      vim.cmd("source " .. theme_script_path)
  end
end

if file_exists(theme_script_path) then
  vim.o.termguicolors = true
  vim.g.tinted_colorspace = 256

  vim.cmd("source " .. theme_script_path)

  vim.api.nvim_create_autocmd("FocusGained", {
    callback = handle_focus_gained,
  })
end
```

but, using the `:colorscheme` command in nvim, it is not found:
![neovim error: E185: Cannot find color scheme 'base24-tinty-generated`](https://github.com/user-attachments/assets/00984c5b-56c8-473a-ac4b-18658a321beb)

**Comment by JamyGolden** [comment]
I think the best way to solve this is to install tinted-nvim slightly differently. Since we need Tinty to build the themes of a template when applying a custom scheme, Tinty needs to have access to that repo.

1. Add `tinted-nvim` to the list of templates to build in your tinty `config.toml`
    Append the following to your `~/.config/tinted-theming/tinty/config.toml` (set the path correctly to your locally cloned version of tinted-nvim)

    ```toml
    [[items]]
    path = "~/projects/tinted-theming/tinted-nvim"
    name = "tinted-nvim"
    themes-dir = "colors"
    supported-systems = ["base16", "base24"]
    ```
2. Make sure you're using a local version of `tinted-nvim` within your plugin manager
    This is what I have in my lazy.nvim setup under `.../plugins/tinted-nvim.lua`

    ```lua
    return {
      "~/tinted-theming/tinted-nvim",
      dev = true,
      config = function()
        require("tinted-colorscheme").setup(nil)
      end
    }
    ```

Let me know if this works for you and thanks again for creating the issue.

**Comment by rwendell** [comment]
A solution that I came up with using tinty hooks:

tinty config:
```yaml
[[items]]
path = "https://github.com/tinted-theming/tinted-nvim"
name = "tinted-nvim"
themes-dir = "colors"
supported-systems = ["base16", "base24"]
hook = "command cp -f %f ~/.config/nvim/colors"
```


plugin init:
```Lua
return {
	{
		"tinted-theming/tinted-nvim",
		config = function()
			vim.cmd([[colorscheme tinted-nvim-colors-file]])
		end
	}
}
```

**Comment by josswright** [comment]
> Great implementation! Mine didn't support live-reload because it only checked through the publicly available repos. Stealing this

Steal away! :)

One thing I have noticed is that live reload doesn't seem to work for iterating on a scheme--it won't apply changes to a theme if you edit it after being applied and then rerunning `tinty apply`. (Even if you first apply another scheme and go back to the altered one.) Not really a huge problem, as it's a bit of a niche case, but I thought I'd mention it.

**Comment by josswright** [comment]
> Yeah, that happened to me too. I think it's how nvim loads the colorscheme registry.  Have you considered raising a pr to integrate your colorscheme into the tinty org? That way you don't need to worry about custom schemes 😏

Fixed it! (Which is nice, as it means that I can iterate on my personal scheme for a while before feeling that I have to push it to the repository.)

It was nagging at me that this only seemed to happen with my custom scheme, and only seemed to affect `lualine`. It just occurred to me that the hook above only copies the _lua_ version of the generated colour scheme to the appropriate place, and not the vimscript version. I've just added that to the hook, and now it's working perfectly. It seems that `lualine`, ironically, must be using the vimscript colours scheme file internally. 🤦‍♂️

So, just for reference, here's a repeated version of the setup I posted above that should work fully now:

(Using [lazy.nvim](https://lazy.folke.io/)).

`$HOME/.nvim/lua/plugins/tinted-nvim.lua`:
```lua

return {
  "tinted-theming/tinted-nvim",
  priority = 1000,
  opts = {
    supports = {
      tinty = true,
      tinted_shell = true,
      live_reload = true,
      transparent = true
    },
    highlights = {
      telescope = true,
      indentblankline = true,
      notify = true,
      ts_rainbow = true,
      cmp = true,
      illuminate = true,
      lsp_semantic = true
    }
  },
  config = function( _, opts )
     require('tinted-colorscheme').setup(nil,opts)
  end
}
```

`$HOME/.config/tinted-theming/tinty/config.toml`:
```toml
...
[[items]]
name = "tinted-nvim"
path = "https://github.com/tinted-theming/tinted-nvim" 
themes-dir = "colors"
supported-systems = ["base16", "base24"]
hook = """
  cp -f $HOME/.local/share/tinted-theming/tinty/repos/tinted-nvim/lua/colors/%n.lua ~/.local/share/nvim/lazy/tinted-nvim/lua/colors/%n.lua; \
  cp -f $HOME/.local/share/tinted-theming/tinty/repos/tinted-nvim/colors/%n.vim ~/.local/share/nvim/lazy/tinted-nvim/colors/%n.vim""" # This is hacky, but works for the moment while developing a custom theme.
...
```
(Note here that I can't use `%f` for the above, because that points only to the `.vim` version, and I couldn't see a way to access the `.lua` version more neatly.)

For completeness, I've also been using this script to wrap around `tinty update` while the issue at https://github.com/tinted-theming/tinted-nvim/issues/33 still applies:

```sh
#!/bin/zsh

# Copy scheme to tinty custom-schemes location
cp </path/to/scheme.yaml> $HOME/.local/share/tinted-theming/tinty/custom-schemes/base24

# Clean up tinted-nvim artefacts from build
pushd $HOME/.local/share/tinted-theming/tinty/repos/tinted-nvim 
git restore {README.md,doc/colorscheme.txt}

# Go back to where we started
popd

# Regenerate schemes
tinty update

# Apply rebuilt scheme
tinty apply <scheme>
```
